import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display } from 'next/font/google'
import { Proza_Libre } from 'next/font/google'


const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  display: 'swap',
  style: ['normal', 'italic']
})

const prozaLibre = Proza_Libre({
  subsets: ['latin'],
  variable: '--font-proza',
  display: 'swap',
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${prozaLibre.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
